### ISSUE TITLE
用背景颜色区分不同按钮

### ISSUE THREAD

**Issue by SpaceThing** [ltxhhz/LL-plugin-list-viewer#1]
希望能将“安装/更新/卸载/重试”四种按钮背景设置不同的颜色，更便于区分
如安装-蓝色，更新-绿色，卸载-红色，重试-无需颜色（插件名为已经为红色）
![截图20240511211841](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/03c6096b-8b15-42bd-a2ee-cdb1546d0694)

**Comment by ltxhhz** [comment]
这个是按钮和样式是定义 [LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/blob/62bb9cef9a5c6901f3ee72de4a9162278d708b2e/src/components/static/style.css#L293-L346) 提供的，你可以先去那边提 issue，如果 LiteLoaderQQNT 改了我就改。

**Comment by SpaceThing** [comment]
这样啊哈哈，好的
