### ISSUE TITLE
点击安装按钮后出现多余折叠箭头

### ISSUE THREAD

**Issue by SpaceThing** [ltxhhz/LL-plugin-list-viewer#10]
两个多余的折叠箭头按钮，可以点击，无反应
复现：点击安装按钮
<img src="https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/ed3514cc-b18e-4c92-a5fb-25cb50974879" width="500px">
<img src="https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/177c40f0-3c0f-49ec-b849-ecf08cbf24a2" width="500px">

**Comment by SpaceThing** [comment]
或许是因为LL默认的setting-section样式原因？

**Comment by ltxhhz** [comment]
请在使用插件前认真阅读自述文件

**Comment by SpaceThing** [comment]
我的😂，没看更新后的readme，辛苦了
