### ISSUE TITLE
弹框背景都是透明的，看不清

### ISSUE THREAD

**Issue by zicai1026** [ltxhhz/LL-plugin-list-viewer#13]
如图：
![微信截图_20240530160820](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/8031864/dda04885-0248-4e45-9d15-6d112a0e08cd)

**Comment by ltxhhz** [comment]
请检查你是不是开了什么主题插件，看看关了主题是否正常

**Comment by zicai1026** [comment]
> 请检查你是不是开了什么主题插件，看看关了主题是否正常

与`MSping Theme`冲突，关掉之后是白色背景，输入框不明显

**Comment by ltxhhz** [comment]
这并不是冲突，是主题没适配
样式不明显下个版本会改
