### ISSUE TITLE
左侧没有插件显示

### ISSUE THREAD

**Issue by henry-us** [ltxhhz/LL-plugin-list-viewer#15]
可以看到加载了该插件，但是没有显示UI界面，
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/49888091/0ce1529c-88a3-4bd1-b097-9e8310969d6f)

**Comment by henry-us** [comment]
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/49888091/6add70ff-623c-437c-8b14-c3f1f73a5ebb)

**Comment by ltxhhz** [comment]
设置
