### ISSUE TITLE
构建遇到问题

### ISSUE THREAD

**Issue by LanYunDev** [ltxhhz/LL-plugin-list-viewer#17]
**yarn** (v1.22.22):
$ npx electron-vite build
node:internal/modules/esm/resolve:841
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /Users/lanyun/Library/Containers/com.tencent.qq/Data/Documents/LiteLoaderQQNT/plugins/LL-plugin-list-viewer/node_modules/electron-vite/dist/cli.mjs
    at packageResolve (node:internal/modules/esm/resolve:841:9)
    at moduleResolve (node:internal/modules/esm/resolve:914:18)
    at defaultResolve (node:internal/modules/esm/resolve:1119:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:511:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**npm** (v10.7.0):
➜  LL-plugin-list-viewer git:(main) npm i

added 347 packages, and audited 348 packages in 4s

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
➜  LL-plugin-list-viewer git:(main) ✗ npm run build

> list-viewer@1.2.1 build
> npx electron-vite build

vite v5.2.9 building SSR bundle for production...
✓ 9 modules transformed.
dist/main/index.js  18.01 kB
✓ built in 109ms
vite v5.2.9 building SSR bundle for production...
✓ 1 modules transformed.
dist/preload/index.js  0.31 kB
✓ built in 11ms
vite v5.2.9 building for production...
src/renderer/utils.ts (54:34): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
src/renderer/utils.ts (57:31): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
src/renderer/utils.ts (60:26): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 11 modules transformed.
dist/renderer/index.js  29.70 kB
✓ built in 84ms
Done in 0.0s

Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "src/**/*.js" were found.
Please check for typing mistakes in the pattern.

Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "src/**/*.js" were found.
Please check for typing mistakes in the pattern.

Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "src/**/*.js" were found.
Please check for typing mistakes in the pattern.

**Comment by ltxhhz** [comment]
你是否修改了这部分代码 
https://github.com/ltxhhz/LL-plugin-list-viewer/blob/b79ebbff93383cddbbedaefcd1ae5aaf0f539239/electron.vite.config.ts#L26-L31

**Comment by LanYunDev** [comment]
没有,我直接clone的,未做修改.

**Comment by ltxhhz** [comment]
尝试直接运行 `eslint --fix src/**/*.{ts,js}`，看看行不行
你也可以注释掉上面那部分代码来禁用这条命令

**Comment by LanYunDev** [comment]
尝试直接运行:
终端:
➜  LL-plugin-list-viewer git:(main) ✗ eslint --fix src/**/*.{ts,js}
bash: eslint: 未找到命令

注释后:
<img width="696" alt="image" src="https://github.com/ltxhhz/LL-plugin-list-viewer/assets/95263282/ead70ab9-24a2-4cb7-a602-3ce1c0cf5f7d">

终端:
➜  LL-plugin-list-viewer git:(main) ✗ yarn run build
依然报错:
yarn run v1.22.22
$ npx electron-vite build
node:internal/modules/esm/resolve:841
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /Users/lanyun/Library/Containers/com.tencent.qq/Data/Documents/LiteLoaderQQNT/plugins/LL-plugin-list-viewer/node_modules/electron-vite/dist/cli.mjs
    at packageResolve (node:internal/modules/esm/resolve:841:9)
    at moduleResolve (node:internal/modules/esm/resolve:914:18)
    at defaultResolve (node:internal/modules/esm/resolve:1119:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:511:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ltxhhz** [comment]
注释后的错误已经不是那个了，你再安装一次依赖就好了

**Comment by LanYunDev** [comment]
删除node_modules,重新yarn install安装依赖,再构建yarn run build,一样的报错

**Comment by ltxhhz** [comment]
你第一次发的记录，用npm安装不是没报 `ERR_MODULE_NOT_FOUND` 正常运行了吗

![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/51697596/41f9a997-0d5c-4bc2-ad08-c34e4aca1047)

**Comment by LanYunDev** [comment]
我主要想表达使用yarn构建失败,npm报“Something went wrong”的错误
下面是注释后后使用NPM的命令运行结果
➜  LL-plugin-list-viewer git:(main) ✗ npm install

added 56 packages, removed 34 packages, changed 67 packages, and audited 348 packages in 4s

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
➜  LL-plugin-list-viewer git:(main) ✗ npm run build

> list-viewer@1.2.1 build
> npx electron-vite build

vite v5.2.9 building SSR bundle for production...
✓ 9 modules transformed.
dist/main/index.js  18.01 kB
✓ built in 102ms
vite v5.2.9 building SSR bundle for production...
✓ 1 modules transformed.
dist/preload/index.js  0.31 kB
✓ built in 6ms
vite v5.2.9 building for production...
src/renderer/utils.ts (54:34): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
src/renderer/utils.ts (57:31): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
src/renderer/utils.ts (60:26): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 11 modules transformed.
dist/renderer/index.js  29.70 kB
✓ built in 56ms
Done in 0.0s

Oops! Something went wrong! :(

ESLint: 8.57.0

No files matching the pattern "src/**/*.js" were found.
Please check for typing mistakes in the pattern.

**Comment by ltxhhz** [comment]
注释之后是不会再执行eslint的，也就不应该有eslint的报错，我在Windows平台开发的，不知道你这里是为什么还会执行

另外看起来已经有输出了，你可以把manifest.json和assets复制到dist，然后拿dist目录下的东西去用，这个报错之后也就只有个复制和压缩而已

**Comment by LanYunDev** [comment]
我将electron.vite.config.ts中包含viteChecker相关代码部分 **都** 给注释掉后使用NPM运行结果:
➜  LL-plugin-list-viewer git:(main) ✗ npm install

added 347 packages, and audited 348 packages in 2s

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
➜  LL-plugin-list-viewer git:(main) ✗ npm run build

> list-viewer@1.2.1 build
> npx electron-vite build

vite v5.2.9 building SSR bundle for production...
✓ 9 modules transformed.
dist/main/index.js  18.01 kB
✓ built in 105ms
vite v5.2.9 building SSR bundle for production...
✓ 1 modules transformed.
dist/preload/index.js  0.31 kB
✓ built in 5ms
vite v5.2.9 building for production...
src/renderer/utils.ts (54:34): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
src/renderer/utils.ts (57:31): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
src/renderer/utils.ts (60:26): Use of eval in "src/renderer/utils.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 11 modules transformed.
dist/renderer/index.js  29.70 kB
✓ built in 40ms
Done in 0.0s
[unplugin-zip-pack] Success: /Volumes/2T/Downloads/LL-plugin-list-viewer/list-viewer.zip has been generated.

看起来似乎没问题.

如果我使用yarn安装依赖并进行构建将会出错.命令日志如下:
➜  LL-plugin-list-viewer git:(main) ✗ yarn install
yarn install v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
[2/4] 🚚  Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
warning vite-plugin-cp@4.0.8: The engine "vite" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning "@typescript-eslint/eslint-plugin > ts-api-utils@1.3.0" has unmet peer dependency "typescript@>=4.2.0".
warning " > @electron-toolkit/tsconfig@1.0.1" has unmet peer dependency "@types/node@*".
warning " > electron-vite@2.1.0" has unmet peer dependency "vite@^4.0.0 || ^5.0.0".
warning " > vite-plugin-checker@0.6.4" has unmet peer dependency "vite@>=2.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 22.32s.
➜  LL-plugin-list-viewer git:(main) ✗ yarn run build
yarn run v1.22.22
$ npx electron-vite build
node:internal/modules/esm/resolve:841
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /Volumes/2T/Downloads/LL-plugin-list-viewer/node_modules/electron-vite/dist/cli.mjs
    at packageResolve (node:internal/modules/esm/resolve:841:9)
    at moduleResolve (node:internal/modules/esm/resolve:914:18)
    at defaultResolve (node:internal/modules/esm/resolve:1119:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:511:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:126:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ltxhhz** [comment]
我这里也是用 npm，你 npm 执行后似乎也生成成功了

如果你想用 yarn，可以尝试删除 `package-lock.json` 文件再安装依赖再尝试，如果还有问题我这里无法提供更多帮助，因为我对 yarn 也不是很了解

**Comment by LanYunDev** [comment]
我刚刚修复了下,我准备提个pull,作者你倾向保留viteChecker代码还是移除?

**Comment by ltxhhz** [comment]
留着

**Comment by LanYunDev** [comment]
https://github.com/ltxhhz/LL-plugin-list-viewer/pull/18
