### ISSUE TITLE
刷新功能异常

### ISSUE THREAD

**Issue by jy02534655** [ltxhhz/LL-plugin-list-viewer#2]
插件列表已有数据的情况下点刷新会发现获取到的数据有重复项，再点一次刷新恢复正常

**Comment by ltxhhz** [comment]
俺的图图呢？还有如何稳定重现？

**Comment by jy02534655** [comment]
没复现到，可能是在网络很慢的时候，然后边加载边往下滚动就会出现重复项？是用了虚拟滚动的原因？

**Comment by SpaceThing** [comment]
刚刚出现了一次
![u52j1d3c jci](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/0c357c7c-e31b-46ce-9309-b01cca9d3b15)

**Comment by jy02534655** [comment]
> 俺的图图呢？还有如何稳定重现？

![QQ截图20240520120215](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/4277777/eca6bffa-dc6e-45f9-8d75-514d355bfc2f)
![QQ截图20240520120225](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/4277777/2ef75911-ae6f-4476-b9a3-f4b1e65476ac)
![QQ截图20240520120241](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/4277777/8ce0a36a-18c4-4f08-a290-e94c003da137)
复现了，不知道咋个稳定复现，感觉是虚拟滚动的问题
