### ISSUE TITLE
[bug] Releases manifest.json 版本号未更新

### ISSUE THREAD

**Issue by pure-white-ice-cream** [ltxhhz/LL-plugin-list-viewer#21]
会导致如图情况, 图中已经是 1.3.1 版本
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61543584/c0139c8c-964e-4381-8a9d-db3d893de923)

**Comment by ltxhhz** [comment]
改版本之后忘了重新打包了

**Comment by ltxhhz** [comment]
已更新
