### ISSUE TITLE
[BUG] 接口重定向导致插件列表获取失败

### ISSUE THREAD

**Issue by QingFeng-awa** [ltxhhz/LL-plugin-list-viewer#22]
插件列表没有显示,刷新多少次都没有用,镜像试了5个,关闭镜像使用了Watt Toolkit系统代理和Clash,都没有用……
> 不太确定是不是因为网络问题,但是镜像和加速器不会同一时间这么巧合的故障吧?

![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/151742581/634d1353-7e75-49e1-ad03-86d0d3e43c9c)

**Comment by ltxhhz** [comment]
版本信息提供一下

**Comment by QingFeng-awa** [comment]
v1.3.1

**Comment by ltxhhz** [comment]
qq版本
loader版本

**Comment by QingFeng-awa** [comment]
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/151742581/763d07b5-e0f9-4663-9f6a-19f162ba4b76)

**Comment by ltxhhz** [comment]
根据我的测试，目前自带的镜像可以正常获取到，你可以再检查一下

不使用镜像时，前端请求的重定向似乎有问题，导致请求失败，这个之后应该会修复
