### ISSUE TITLE
更新插件自身时报错，只能手动更新

### ISSUE THREAD

**Issue by jy02534655** [ltxhhz/LL-plugin-list-viewer#24]
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/4277777/9d8d594d-e22e-4af1-bec1-063a3dfd2baf)

**Comment by PBMoose** [comment]
+1

**Comment by ltxhhz** [comment]
哪个版本向哪个版本升级

**Comment by jy02534655** [comment]
1.3.2 -> 1.3.3 ,1.3.1 -> 1.3.2 都有这个问题，都是手动升的

**Comment by ltxhhz** [comment]
是不是会报错两次，第一次是`Malicious entry: assets\icon.svg`

**Comment by ltxhhz** [comment]
已经定位到问题，下个版本修复
