### ISSUE TITLE
[Enhancement] 在manifest.json中添加配置项指定更新该插件时使用的包

### ISSUE THREAD

**Issue by adproqwq** [ltxhhz/LL-plugin-list-viewer#25]
rt
像本插件及其他类似的使用TypeScript编写的插件，使用源码包下载、更新会出现报错，但用户有可能盲目选择源码包。
或许可以通过提供一个manifest配置项，使插件可以自定义该插件可使用的更新方式。
具体表现为：当某插件指定仅可使用release包更新时，源码更新按钮不可见或不可点击，或其他方法阻止用户选择源码包更新。

**Comment by ltxhhz** [comment]
我认为可以添加一个说明去引导用户查看应该选择哪一种，而不是让其他插件来添加配置项进行适配，因为不一定所有开发者会愿意为了我这个插件而增加配置项，而且还增加双方工作量

**Comment by ltxhhz** [comment]
刚看了一下 [PluginInstaller](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller) 的例子，只有你的插件添加了，[LLOneBot](https://github.com/LLOneBot/LLOneBot) 是明确说明了不能通过在线商店安装的也没添加对吧
其他开发者没有义务做这件事，更何况有些插件也不更新了更不会加

![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/51697596/2cfb141c-3bd8-4598-af27-a0b0913994ac)

**Comment by adproqwq** [comment]
的确。你的方案是要比我的好些。

**Comment by ltxhhz** [comment]
已经修改，但暂时不会发布新版
