### ISSUE TITLE
[Feat] 升级qqnt9.9.12-25493版本导致按钮样式改变

### ISSUE THREAD

**Issue by QingFeng-awa** [ltxhhz/LL-plugin-list-viewer#26]
没有任何插件干预的情况下,插件的`卸载`与`安装`按钮颜色是一样的,如图所示。
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/151742581/8564437b-9841-4a06-b0c7-db56a97f681f)
个人认为这两个不太容易分辨,故希望`卸载`按钮移除背景颜色。(同时将边框颜色改为原背景色)

**Comment by ltxhhz** [comment]
你确定没有其他插件吗

**Comment by QingFeng-awa** [comment]
是的,我把其它插件全部禁用了。
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/151742581/fab9c931-0176-4272-a496-35bdf0eb8019)

![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/151742581/8e3bbe40-47ba-4b3b-b672-a7193503e66e)

**Comment by ltxhhz** [comment]
LiteLoader版本信息截个图
LiteLoader是release版本吗

**Comment by QingFeng-awa** [comment]
LL是release版本。
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/151742581/0efbc8b9-d678-428a-a22e-c2b3fc5d636d)

**Comment by ltxhhz** [comment]
新版本qq导致的LiteLoader不兼容，去那边提issue或者降级qq

**Comment by ltxhhz** [comment]
已修复 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pull/328
