### ISSUE TITLE
每次更新都会出现这个

### ISSUE THREAD

**Issue by PBMoose** [ltxhhz/LL-plugin-list-viewer#28]
然后就会自动删除目录插件，需要手动下载然后复制到文件
![QQ20240718-090233](https://github.com/user-attachments/assets/f4b63bd7-61ae-40d5-84e7-a21099cfd98e)

**Comment by ltxhhz** [comment]
版本信息？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ltxhhz/LL-plugin-list-viewer] 每次更新都会出现这个 (Issue #28)




 
然后就会自动删除目录插件，需要手动下载然后复制到文件
 QQ20240718-090233.png (view on web)

**Comment by PBMoose** [comment]
从1.3.2开始就一直出现，每次都要手动下载文件才能更新

**Comment by ltxhhz** [comment]
重复 #24

**Comment by letterk** [comment]
@ltxhhz 1.3.4升级1.3.5依然是同样的报错

**Comment by ltxhhz** [comment]
@letterk 刚试了，并没有问题
![image](https://github.com/user-attachments/assets/5166a15f-72f8-4864-b638-7d55390d2f45)
