### ISSUE TITLE
[bug] 升级LiteLoader 1.2.0 导致默认图标闪动

### ISSUE THREAD

**Issue by jy02534655** [ltxhhz/LL-plugin-list-viewer#30]
### qq版本

9.9.12-25765

### LiteLoader 版本

1.2.0

### 版本信息

![QQ_1722476180116](https://github.com/user-attachments/assets/260852a9-12d9-4ef5-96a2-94c37e747e8b)

### list-viewer 插件版本

1.3.6

### LiteLoader 是否为发布版本(release)

是

### 问题描述

![QQ_1722476093658](https://github.com/user-attachments/assets/f434beed-cd7b-4d6f-828d-f7a7a8c22479)
LiteLoader 更新后部分组件图标无法显示，并且不断的闪动

### 重现步骤

直接就能看到

**Comment by pure-white-ice-cream** [comment]
遇到相同问题, 部分组件图标无法显示，并且不断的闪动
![image](https://github.com/user-attachments/assets/21685a33-598a-4e17-add6-a82622256eb9)

**Comment by ltxhhz** [comment]
@pure-white-ice-cream 你的版本信息提供下

**Comment by pure-white-ice-cream** [comment]
> @pure-white-ice-cream 你的版本信息提供下

LiteLoader
1.2.0

QQNT
9.9.12-26466

list-viewer
1.3.6

**Comment by pure-white-ice-cream** [comment]
> > @pure-white-ice-cream 你的版本信息提供下
> 
> LiteLoader 1.2.0
> 
> QQNT 9.9.12-26466
> 
> list-viewer 1.3.6

(1.3.5 也出现相同问题)

**Comment by ltxhhz** [comment]
~~目前来看是新版框架或者 qq 的 bug~~是框架图片的路径改了，下版本修复
