### ISSUE TITLE
使用release包方式无法下载插件

### ISSUE THREAD

**Issue by SakiBiAnNya** [ltxhhz/LL-plugin-list-viewer#31]
### qq版本

9.9.12

### LiteLoader 版本

1.2

### 版本信息

![e9b19839cd8f966d654bdac9369c37df](https://github.com/user-attachments/assets/2805ec6a-90e1-4f64-bc5b-cbfe08a9c63a)

### list-viewer 插件版本

1.3.7

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Windows10 pro 22h2

### 问题描述

已挂梯（全局），安装插件时，使用release包方式无法下载，提示Cannot read properties of undefined(reading 'find')
![9a0d0183ad394b68d7329ab939d32ac1](https://github.com/user-attachments/assets/e3e169e2-1a0a-45d8-90c0-2c7ab39af03e)

### 重现步骤

无

**Comment by ltxhhz** [comment]
下载哪个插件出现的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月3日(周六) 中午12:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ltxhhz/LL-plugin-list-viewer] 使用release包方式无法下载插件 (Issue #31)




 
qq版本
 
9.9.12
 
LiteLoader 版本
 
1.2
 
版本信息
 
e9b19839cd8f966d654bdac9369c37df.png (view on web)
 
list-viewer 插件版本
 
1.3.7
 
LiteLoader 是否为发布版本(release)
 
是
 
使用平台
 
Windows10 pro 22h2
 
问题描述
 
已挂梯（全局），安装插件时，使用release包方式无法下载，提示Cannot read properties of undefined(reading 'find')
 9a0d0183ad394b68d7329ab939d32ac1.png (view on web)
 
重现步骤
 
无
 
期待的正确结果
 
No response
 
相关日志输出
 
No response
 
附加信息
 
No response

**Comment by SakiBiAnNya** [comment]
> 下载哪个插件出现的

全部插件都是显示这样

**Comment by SakiBiAnNya** [comment]
> 下载哪个插件出现的
可以用仓库方式下载成功，但下载完后显示未激活，重启qq也没安装上（轻量工具箱）
![a9cc1db22d65f45f0651f46f6ccd6e20](https://github.com/user-attachments/assets/1a10c995-5697-4cb4-b777-d315158ce0ce)

**Comment by ltxhhz** [comment]
有些插件不支持仓库安装的，这个问题等我稍后看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月3日(周六) 中午12:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ltxhhz/LL-plugin-list-viewer] 使用release包方式无法下载插件 (Issue #31)




  
下载哪个插件出现的
 可以用仓库方式下载成功，但下载完后显示未激活，重启qq也没安装上（轻量工具箱）
 a9cc1db22d65f45f0651f46f6ccd6e20.png (view on web)

**Comment by ltxhhz** [comment]
你在浏览器访问一下 [https://api.github.com/repos/xiyuesaves/LiteLoaderQQNT-lite_tools/releases/latest](https://api.github.com/repos/xiyuesaves/LiteLoaderQQNT-lite_tools/releases/latest)
看下能不能正常访问，因为这个问题大概率是你的网络问题

**Comment by SakiBiAnNya** [comment]
> 您在浏览器访问一下https://api.github.com/repos/xiyuesaves/LiteLoaderQQNT-lite_tools/releases/latest 看下能不能正常访问，因为这个问题很大概率是您的网络问题

访问输出：
{
  "message": "API rate limit exceeded for 38.207.143.79. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}

**Comment by ltxhhz** [comment]
那就对了，你这个ip访问api次数太多了导致的这个问题
下个版本我会优化提示

**Comment by jhqwqmc** [comment]
@ltxhhz 能否在请求的头部添加[GITHUB_TOKEN](https://github.com/settings/tokens)来缓解这个问题
```json
{
    "Authorization": "Bearer ghp_xxxxx",
    "X-GitHub-Api-Version": "2022-11-28"
}
```

**Comment by ltxhhz** [comment]
下次一定



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 凌晨0:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ltxhhz/LL-plugin-list-viewer] 使用release包方式无法下载插件 (Issue #31)




 
@ltxhhz 能否在请求的头部添加GITHUB_TOKEN来缓解这个问题
 {     "Authorization": "Bearer ghp_xxxxx",     "X-GitHub-Api-Version": "2022-11-28" }
