### ISSUE TITLE
[feature]希望添加 Transitio 和 scriptio 的列表,可以显示和安装这两个插件能加载的内容

### ISSUE THREAD

**Issue by yhzcake** [ltxhhz/LL-plugin-list-viewer#32]
### qq版本

9.9.12-26466

### LiteLoader 版本

1.2.-

### 版本信息

![image](https://github.com/user-attachments/assets/b680432a-86ec-4ebc-808f-cf5dcf0a53a3)

### list-viewer 插件版本

1.3.8

### LiteLoader 是否为发布版本(release)

是

### 请描述您的需求或者改进建议

希望在列表中两个插件右侧的按钮中添加一个css/js列表用于查看和下载相关内容

### 请描述你建议的实现方案

在两个插件的read.me里面列出了相关的内容,但是看起来貌似并不适合做成列表

**Comment by ltxhhz** [comment]
这个应该由这两个插件自身新增的功能，我为了个别插件单独开发新功能是没必要的

**Comment by yhzcake** [comment]
这两个插件的作者貌似也没有计划..另外之前的插件商店(没了的那个)有这个功能,所以我才问,没有计划就算了(((

**Comment by ltxhhz** [comment]
如果我做了，插件的脚本列表只有原作者那里有，并且不是序列化的数据，现在是md格式的table，之后随时可能变成其他样式，或者他的插件的安装目录变了，如果变了这边就得跟着他做适配，可以算是在维护其他人的功能了，这属于额外的工作量了，换做其他人也不一定会做的，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月11日(周日) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ltxhhz/LL-plugin-list-viewer] [feature]希望添加 Transitio 和 scriptio 的列表,可以显示和安装这两个插件能加载的内容 (Issue #32)




 
这两个插件的作者貌似也没有计划..另外之前的插件商店(没了的那个)有这个功能,所以我才问,没有计划就算了(((

**Comment by yhzcake** [comment]
了解,这确实是很大的问题
