### ISSUE TITLE
我不会在linux上解压，请帮帮我

### ISSUE THREAD

**Issue by Cjsah** [ltxhhz/LL-plugin-list-viewer#35]
### qq版本

不重要

### LiteLoader 版本

不重要

### 版本信息

![image](https://github.com/user-attachments/assets/3a8f45da-3dd6-4d94-b65e-1a92b396aa83)

### list-viewer 插件版本

1.3.10

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Linux(Debian 12.5 KDE)

### 问题描述

系统无法识别成压缩包, 通过软件强制打开后, 文件夹结构全都消失
![image](https://github.com/user-attachments/assets/0072e042-113c-4f88-87d8-de6ae0bb8217)
![image](https://github.com/user-attachments/assets/3088c1a0-5e3b-4cfd-8cb0-030a6e3f704a)

正常可以识别的压缩包右键菜单是这样的
![1](https://github.com/user-attachments/assets/f04c2de0-8efc-415c-93f1-e94ffd5e4409)

### 重现步骤

下载就可以复现

**Comment by ltxhhz** [comment]
1. 要么你可以选择用unzip命令解压
![QQ_1723688688859](https://github.com/user-attachments/assets/4510902f-7334-4041-aad4-b9db3be635a4)

2. 要么你可以选择第一个 ark 工具打开来处理
3. 对 Linux 不熟悉可以使用 Windows

**Comment by Cjsah** [comment]
1. unzip没问题
2. ark处理有问题, 截图里有
3. 有问题还不能反馈吗? 关我linux熟不熟悉啥关系, 我爱咋用咋用

**Comment by Cjsah** [comment]
![image](https://github.com/user-attachments/assets/d3a58969-401e-4908-ba91-78badd7dc236)
ark解压后就是这样的

**Comment by ltxhhz** [comment]
你这人真奇怪
![QQ_1723690151982](https://github.com/user-attachments/assets/f92b9c96-854a-41dc-9b94-addb188f74b9)

首先，自述最开头就说了，不保证其他平台可用性
![QQ_1723690069199](https://github.com/user-attachments/assets/3dc23c99-e231-4a9f-a8aa-dcf9061c842b)

所以你不认真看自述文件，按理来说我都没义务帮你，但我还是给你三个解决方案，根据你的反馈：
1. unzip已经能解决你的问题，但你还在这纠缠
2. 哪怕ark有问题也和我无关
3. 你已经反馈了，而我也给了解决方案，其次我只是建议你使用 Windows 又不是逼你用，你急什么

**Comment by Cjsah** [comment]
我把信息给全了, 反馈是希望解决的 又不是希望被嘲讽的

**Comment by ltxhhz** [comment]
> 我把信息给全了, 反馈是希望解决的 又不是希望被嘲讽的

1. “建议”在你这为什么等于“嘲讽”
2. 关于分隔符的问题，之前的 issue #16 有，你为什么不看 issue 就来提了，而且还提两次

**Comment by Cjsah** [comment]
你也说了 未对其他平台测试, 所以我遇到问题了, 跟你反馈没问题吧?

**Comment by ltxhhz** [comment]
> 你也说了 未对其他平台测试, 所以我遇到问题了, 跟你反馈没问题吧?

你玩原神么

**Comment by Cjsah** [comment]
不是 咋啥都能扯这玩意上去

**Comment by Cjsah** [comment]
> 你也说了 未对其他平台测试, 所以我遇到问题了, 跟你反馈没问题吧?

你没对其他平台测试, 所以我遇到了, 我反馈了, 希望解决, 然后你来了一句`对 Linux 不熟悉可以使用 Windows`
这谁不火大啊

**Comment by CyanChanges** [comment]
您好反馈 Ark 问题可以前往 <https://bugs.kde.org/> 谢谢, 这里不是 KDE 的 repo

**Comment by CyanChanges** [comment]
1. 对于和 repo 内容无关的, 开发者完全没有必要去解决你的问题, 给你提出方案已经很好了
2. Ark 是 KDE 开发的
3. 一行 shell 命令就可以解决的事情为什么要用 GUI 啊?
4. 为您找到以下类似内容: 
<details>
- 所以我遇到问题了: 写作业, 我作业看不懂, 作业的语言有问题, 我看不懂英文, 和作业出题人反馈没问题吧?   <br>
- 作业出题人: ?????
</details>

**Comment by CyanChanges** [comment]
> 您好反馈 Ark 问题可以前往 https://bugs.kde.org/ 谢谢, 这里不是 KDE 的 repo

友情提示: Ark 有些格式打不开是老问题了, 中间忘了, 理论上可以改配置也许能开, 后面忘了

**Comment by Cjsah** [comment]
难道都是不看问题的吗? 下面作者也回复了, windows压成了反斜杠导致的问题, 关人ark什么关系
归根结底我火大的是 作者回第三点
希望处理的是斜杠的问题
哎，都说是我的问题 那就是我的问题吧
> 关于分隔符的问题，之前的 issue https://github.com/ltxhhz/LL-plugin-list-viewer/issues/16 有，你为什么不看 issue 就来提了，而且还提两次

**Comment by CyanChanges** [comment]
> 难道都是不看问题的吗? 下面作者也回复了, windows压成了反斜杠导致的问题, 关人ark什么关系 归根结底我火大的是 作者回第三点 希望处理的是斜杠的问题 哎，都说是我的问题 那就是我的问题吧
> 
> > 关于分隔符的问题，之前的 issue #16 有，你为什么不看 issue 就来提了，而且还提两次

谁说的

> * ark处理有问题, 截图里有

**Comment by Cjsah** [comment]
我的意思是, 用ark解压这个压缩包是会出现错误的文件结构
不是都不看上下文的嘛, 要不作者还是给lock了吧

**Comment by CyanChanges** [comment]
按你这么说, 那可能还是 Windows 的实现问题:
https://superuser.com/questions/1382839/zip-files-expand-with-backslashes-on-linux-no-subdirectories

**Comment by CyanChanges** [comment]
> 我的意思是, 用ark解压这个压缩包是会出现错误的文件结构 不是都不看上下文的嘛, 要不作者还是给lock了吧

你这前后矛盾啊

> ark处理有问题, 截图里有

> windows压成了反斜杠导致的问题, 关人ark什么关系

**Comment by Cjsah** [comment]
算了 你说啥是啥
那就是我的问题吧

**Comment by CyanChanges** [comment]
总结一下, 
- Ark 没有处理好 Windows 的非标准的 zip 
- Windows 没有遵循 Zip 规范[1], 压出来非标准的使用 baskslash 作为路径分割符的 zip

[1]. 这东西已经几年了, 但我好久没用 Windows 了, 不到是三方软件实现的问题还是

**Comment by ltxhhz** [comment]
这个 issue我最开始的评论给出的解决方案中的1(使用unzip)已经解决了问题
现在的问题出在这里:
> 有问题还不能反馈吗? 关我linux熟不熟悉啥关系, 我爱咋用咋用

你总觉得我在嘲讽你，你爱用我也管不了，但用着有问题就不应该找我，不是吗

**Comment by CyanChanges** [comment]
> 这个 issue我最开始的评论给出的解决方案中的1(使用unzip)已经解决了问题 现在的问题出在这里:
> 
> > 有问题还不能反馈吗? 关我linux熟不熟悉啥关系, 我爱咋用咋用
> 
> 你总觉得我在嘲讽你，你爱用我也管不了，但用着有问题就不应该找我，不是吗

这个问题其实主要还是 Windows 没符合 zip 规范的问题，
只不过 @Cjsah 一会儿说 Ark 一会儿说是 Win 的问题和 Ark 没关系

**Comment by Cjsah** [comment]
> 你总觉得我在嘲讽你，你爱用我也管不了，但用着有问题就不应该找我，不是吗

那就是我语文有问题吧, 🟥🌡了当时

> 你这前后矛盾啊
> 
> > ark处理有问题, 截图里有
> 
> > windows压成了反斜杠导致的问题, 关人ark什么关系

win没处理好斜杠问题, 所以导致ark解压这个压缩包是会出现错误的文件结构, 这咋就前后矛盾了?
也许也可以归类成我语文的问题

> 所以lock了吧? 都总结完了, 没有讨论的必要了啊
