### ISSUE TITLE
插件压缩包格式有问题, 我new issue好吧

### ISSUE THREAD

**Issue by Cjsah** [ltxhhz/LL-plugin-list-viewer#36]
### list-viewer 插件版本

1.3.10

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Linux

### 问题描述

还是那个问题
unzip能正常解压说明他兼容性确实好, 反斜杠当成正斜杠处理了
但是包括ark和kde都没有处理反斜杠, 所以目录结构丢失
你看这文件夹结构正常吗?

![image](https://github.com/user-attachments/assets/d3a58969-401e-4908-ba91-78badd7dc236)

在就是关于 #35 , 你为什么认为问题是出在我身上, 问题不让反馈吗? 熟悉linux就非要什么操作都用bash吗? 能用鼠标点两下的事情我为什么非要去终端里输命令?
我遇到问题了, 跟你反馈, 是希望能被解决, 而不是希望被嘲讽不会用linux, 而且还是在没有读完问题的情况下

### 重现步骤

#35

**Comment by OiCkilL** [comment]
MacOS 上也有一样的问题，不过只会在settings里更新才会重现
<img width="1032" alt="截屏2024-08-15 11 03 47" src="https://github.com/user-attachments/assets/936fbf8b-8f4e-4b84-ab44-c844d8c59424">

**Comment by Cjsah** [comment]
行吧, 我也去分享一下去,

**Comment by ltxhhz** [comment]
> 在就是关于 https://github.com/ltxhhz/LL-plugin-list-viewer/issues/35 , 你为什么认为问题是出在我身上, 问题不让反馈吗? 熟悉linux就非要什么操作都用bash吗? 能用鼠标点两下的事情我为什么非要去终端里输命令?
> 我遇到问题了, 跟你反馈, 是希望能被解决, 而不是希望被嘲讽不会用linux, 而且还是在没有读完问题的情况下

我都懒得说你了

**Comment by Cjsah** [comment]
行吧, 我也去分享一下去, 一个分割符问题, 能扯到解压

**Comment by ltxhhz** [comment]
> MacOS 上也有一样的问题，不过只会在settings里更新才会重现 <img alt="截屏2024-08-15 11 03 47" width="1032" src="https://private-user-images.githubusercontent.com/613988/358095920-936fbf8b-8f4e-4b84-ab44-c844d8c59424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTE0NjksIm5iZiI6MTcyMzY5MTE2OSwicGF0aCI6Ii82MTM5ODgvMzU4MDk1OTIwLTkzNmZiZjhiLThmNGUtNGI4NC1hYjQ0LWM4NDRkOGM1OTQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwMzA2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTQyNTVkYjk1MTlkNTViYzAxYWQwNjUyM2IxZjNmZDdiZWY1ZDdmYTRkM2VjNjI3Y2Q5NmEwMjcwNTk5NjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EY8DNFgOhwAhH23r3XuZKRtLbq00MbhIc0YNRdYDSEk">

macos我这里同样无法测试，可以选用其他软件试试

**Comment by sj817** [comment]
吃瓜~

**Comment by yigekuyou** [comment]
开发者可以不支持任何平台，不喜欢Linux可以写禁止Linux用户使用

**Comment by alex3236** [comment]
> 开发者可以不支持任何平台，不喜欢Linux可以写禁止Linux用户使用

README“不保证可用性”足矣，这种issue但凡放别的地方早off-topic全lock了（
