### ISSUE TITLE
[feature]能不能单独设置HTTP/SOCK5代理, 为了避免使用全局代理

### ISSUE THREAD

**Issue by Huyil** [ltxhhz/LL-plugin-list-viewer#38]
### qq版本

9.9.15-27391

### LiteLoader 版本

1.2.1

### 版本信息

![image](https://github.com/user-attachments/assets/9e50d289-08a7-4cf3-a27d-b2c15cdf69c4)

### list-viewer 插件版本

1.3.10

### LiteLoader 是否为发布版本(release)

是

### 请描述您的需求或者改进建议

如题, 希望支持配置HTTP以加速访问Github

**Comment by ltxhhz** [comment]
我之前想过这个功能，但我当时没添加这个功能的原因是：
1. 只需要在打开设置前打开全局代理，并且关闭设置后关闭全局代理，不是特别麻烦的事。
2. 渲染层代码默认用 fetch，可以在控制台看到请求，方便调试，由后端发不好调试

**Comment by ltxhhz** [comment]
需要的用户多的话我就加，可以留言
超过10人就加
