### ISSUE TITLE
更新插件时报错

### ISSUE THREAD

**Issue by EmptyDreams** [ltxhhz/LL-plugin-list-viewer#39]
### qq版本

9.9.15-27597

### LiteLoader 版本

1.2.1

### 版本信息

![image](https://github.com/user-attachments/assets/aa979fe4-1728-4f5e-bdef-f4e38fb5f6bb)

### list-viewer 插件版本

1.3.10

### LiteLoader 是否为发布版本(release)

是

### 使用平台

windows10

### 问题描述

![image](https://github.com/user-attachments/assets/ea52bf73-14db-4a4b-b28a-3af584b9429a)

![image](https://github.com/user-attachments/assets/4b1de963-749b-431b-8457-4b58b5e39e38)

### 重现步骤

更新防撤回插件，选择使用 `release` 包，然后就会报错。

**Comment by ltxhhz** [comment]
二进制依赖没办法在 qq 开着的时候被更新，这是 nodejs 的缺陷

**Comment by ltxhhz** [comment]
之后做一个手动更新的吧
