### ISSUE TITLE
插件打开显示空白

### ISSUE THREAD

**Issue by xingleiwu** [ltxhhz/LL-plugin-list-viewer#4]
qq版本为
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/13015600/2be05552-e617-42fd-ba7b-557982696fcd)
插件为最新版本
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/13015600/a9569bc4-61de-4fc0-8ee9-fb2f1f9bc36d)
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/13015600/da58a397-3a70-444d-b1d1-d6813128991e)
电脑版本 win10专业版
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/13015600/8d28cbc3-1aad-4483-b8e2-49a565803aac)
请问x需要怎么检查bug  我可以全力配合  谢谢

**Comment by ltxhhz** [comment]
fixed

**Comment by xingleiwu** [comment]
为什么关闭了  有解决方法吗？
