### ISSUE TITLE
提示获取插件列表失败，开启全局代理，也没解决

### ISSUE THREAD

**Issue by flyinghmx** [ltxhhz/LL-plugin-list-viewer#40]
### qq版本

版本: 9.9.15-27391 (64位)

### LiteLoader 版本

1.2.1

### 版本信息

![微信截图_20240903101438](https://github.com/user-attachments/assets/a9f12e7c-1a7c-4882-bc0e-cfd30a0e970c)

### list-viewer 插件版本

1.3.10

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Windows 10

### 问题描述

![微信图片_20240903101324](https://github.com/user-attachments/assets/d78a540c-e1e9-48fa-bfc2-e26555d21cb3)

### 重现步骤

打开页面，提示获取列表失败

**Comment by ltxhhz** [comment]
你用代理为什么还勾选使用镜像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月3日(周二) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ltxhhz/LL-plugin-list-viewer] 提示获取插件列表失败，开启全局代理，也没解决 (Issue #40)




 
qq版本
 
版本: 9.9.15-27391 (64位)
 
LiteLoader 版本
 
1.2.1
 
版本信息
 
_20240903101438.png (view on web)
 
list-viewer 插件版本
 
1.3.10
 
LiteLoader 是否为发布版本(release)
 
是
 
使用平台
 
Windows 10
 
问题描述
 
_20240903101324.png (view on web)
 
重现步骤
 
打开页面，提示获取列表失败
 
期待的正确结果
 
No response
 
相关日志输出
 
No response
 
附加信息
 
No response

**Comment by flyinghmx** [comment]
我关掉也不行呢，白天了反复试了。新版QQ用不惯了，我换回老板的QQ了，界面简洁些。：）

> 你用代理为什么还勾选使用镜像
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月3日(周二) 上午10:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [ltxhhz/LL-plugin-list-viewer] 提示获取插件列表失败，开启全局代理，也没解决 (Issue #40) qq版本 版本: 9.9.15-27391 (64位) LiteLoader 版本 1.2.1 版本信息 _20240903101438.png (view on web) list-viewer 插件版本 1.3.10 LiteLoader 是否为发布版本(release) 是 使用平台 Windows 10 问题描述 _20240903101324.png (view on web) 重现步骤 打开页面，提示获取列表失败 期待的正确结果 No response 相关日志输出 No response 附加信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
