### ISSUE TITLE
[Bug] 通过 Release 下载插件时报错

### ISSUE THREAD

**Issue by Wesley-Young** [ltxhhz/LL-plugin-list-viewer#41]
### qq版本

27597

### LiteLoader 版本

1.2.1

### list-viewer 插件版本

1.4.0

### LiteLoader 是否为发布版本(release)

是

### 使用平台

macOS Sonoma

### 问题描述

<img width="507" alt="image" src="https://github.com/user-attachments/assets/4103a891-5a66-41cf-a473-9d795e0e8efb">

如图所示，无法解析 GitHub API 返回的 Json。

### 重现步骤

使用 1.4.0 版本的插件仓库通过 release 包下载任意一个插件。

### 相关日志输出

```shell
Unexpected token 'R', "
Request fo"... is not valid JSON 
https://api.github.com/repos/xiyuesaves/LiteLoaderQQNT-lite_tools/releases/latest
```

### 附加信息

通过浏览器访问相同的链接，发现可以返回正常的 Json：
```json5
{
    "url": "https://api.github.com/repos/xiyuesaves/LiteLoaderQQNT-lite_tools/releases/173885119",
    "assets_url": "https://api.github.com/repos/xiyuesaves/LiteLoaderQQNT-lite_tools/releases/173885119/assets",
    // ...
}
```

**Comment by ltxhhz** [comment]
插件里设置代理了吗

**Comment by Wesley-Young** [comment]
设置了

**Comment by ltxhhz** [comment]
找到问题了，下个版本修复
