### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by PBMoose** [ltxhhz/LL-plugin-list-viewer#42]
### qq版本

9.9.15-26909

### LiteLoader 版本

1.2.1

### 版本信息

![QQ20240926-100423](https://github.com/user-attachments/assets/227180e4-efd4-4871-84d9-5b1ddcdca188)

### list-viewer 插件版本

1.4.1

### LiteLoader 是否为发布版本(release)

是

### 使用平台

windows

### 问题描述

无论是开代理还是不开，或者不开镜像，都安装失败
![QQ20240926-100414](https://github.com/user-attachments/assets/be5203cc-fe7a-408a-b935-92d8f3796fe9)

### 重现步骤

手动更新

**Comment by ltxhhz** [comment]
token过期了吧

**Comment by PBMoose** [comment]
> token到期怎么办

是的，我在设置里删了，但是删不掉，要到文件里删

**Comment by ltxhhz** [comment]
最新版1.4.2应该解决了这个问题
