### ISSUE TITLE
使用list-viewer安装任何插件后，重启QQ报错，无法进入

### ISSUE THREAD

**Issue by tyrantcwj** [ltxhhz/LL-plugin-list-viewer#45]
### qq版本

9.9.15-28418

### LiteLoader 版本

1.2.2

### 版本信息

![image](https://github.com/user-attachments/assets/bc9931fa-64e4-48e9-93a3-20c7fc55e07b)

### list-viewer 插件版本

1.4.2

### LiteLoader 是否为发布版本(release)

是

### 使用平台

windows10

### 问题描述

![image](https://github.com/user-attachments/assets/ac04fdbb-f1ab-4bba-b88d-fcea95b84803)

### 重现步骤

使用本插件，通过仓库代码包安装插件如：NapCatQQ，重启qq后报错

**Comment by ltxhhz** [comment]
你安装之前看红字提示了吗

**Comment by ltxhhz** [comment]
这是你自己的使用问题，我将关闭这个 issue
同样也不是框架的问题 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/431#issuecomment-2393100616
