### ISSUE TITLE
打开设置页面时插件会持续报错

### ISSUE THREAD

**Issue by WJZ-P** [ltxhhz/LL-plugin-list-viewer#46]
### qq版本

9.9.15-26909

### LiteLoader 版本

1.2.1

### 版本信息

![image](https://github.com/user-attachments/assets/df4dde0a-09e4-45e6-be58-51cb1ae9a342)

### list-viewer 插件版本

1.4.2

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Win11

### 问题描述

![image](https://github.com/user-attachments/assets/e2d3ada9-2484-4343-9d8d-d2bef70cd838)
上图是我所an'zhua安装的所有插件。
每当我打开设置界面时，列表插件会持续报错如下
![image](https://github.com/user-attachments/assets/e0a38371-4621-4570-b19f-65ebc33b5d3f)
报错是循环重复的

### 重现步骤

在安装上述插件时打开设置界面，并打开F12调试界面

### 期待的正确结果

不再报错

### 相关日志输出

```shell
{
    "id": "Function has non-object prototype 'undefined' in instanceof check",
    "runEnv": "render",
    "type": "TypeError",
    "message": "Function has non-object prototype 'undefined' in instanceof check",
    "stacktrace": "TypeError: Function has non-object prototype 'undefined' in instanceof check\n    at [Symbol.hasInstance] (<anonymous>)\n    at local:///E:\\LiteloaderQQNT\\plugins\\list-viewer\\renderer\\index.js:250:24",
    "logType": "JS_GLOBAL_ERR",
    "osMajorType": "10.0.[>=22000]",
    "platform": "win32",
    "arch": "x64",
    "version": "9.9.15",
    "bk": "26909",
    "env": "prod"
}


​ Uncaught TypeError: Function has non-object prototype 'undefined' in instanceof check
    at [Symbol.hasInstance] (<anonymous>)
    at local:///E:\LiteloaderQQNT\plugins\list-viewer\renderer\index.js:250:24
```

**Comment by ltxhhz** [comment]
我稍后看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ltxhhz/LL-plugin-list-viewer] 打开设置页面时插件会持续报错 (Issue #46)




 
qq版本
 
9.9.15-26909
 
LiteLoader 版本
 
1.2.1
 
版本信息
 
image.png (view on web)
 
list-viewer 插件版本
 
1.4.2
 
LiteLoader 是否为发布版本(release)
 
是
 
使用平台
 
Win11
 
问题描述
 
image.png (view on web)
 上图是我所an'zhua安装的所有插件。
 每当我打开设置界面时，列表插件会持续报错如下
 image.png (view on web)
 报错是循环重复的
 
重现步骤
 
在安装上述插件时打开设置界面，并打开F12调试界面
 
期待的正确结果
 
不再报错
 
相关日志输出
 {     "id": "Function has non-object prototype 'undefined' in instanceof check",     "runEnv": "render",     "type": "TypeError",     "message": "Function has non-object prototype 'undefined' in instanceof check",     "stacktrace": "TypeError: Function has non-object prototype 'undefined' in instanceof check\n    at [Symbol.hasInstance] (<anonymous&gt;)\n    at local:///E:\\LiteloaderQQNT\\plugins\\list-viewer\\renderer\\index.js:250:24",     "logType": "JS_GLOBAL_ERR",     "osMajorType": "10.0.[&gt;=22000]",     "platform": "win32",     "arch": "x64",     "version": "9.9.15",     "bk": "26909",     "env": "prod" } ​ Uncaught TypeError: Function has non-object prototype 'undefined' in instanceof check     at [Symbol.hasInstance] (<anonymous&gt;)     at local:///E:\LiteloaderQQNT\plugins\list-viewer\renderer\index.js:250:24
 
附加信息
 
No response

**Comment by WJZ-P** [comment]
请问最近有发release的打算吗，这个bug对我修改插件设置的布局比较影响

**Comment by ltxhhz** [comment]
晚上发



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ltxhhz/LL-plugin-list-viewer] 打开设置页面时插件会持续报错 (Issue #46)




 
请问最近有发release的打算吗，这个bug对我修改插件设置的布局比较影响
