### ISSUE TITLE
获取列表失败 TypeError: Failed to fetch

### ISSUE THREAD

**Issue by lettimepassby** [ltxhhz/LL-plugin-list-viewer#47]
### qq版本

9.9.15-28418

### LiteLoader 版本

1.2.2

### 版本信息

![image](https://github.com/user-attachments/assets/e580056a-0451-41f5-bc1e-3122ca312969)

### list-viewer 插件版本

1.4.3

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Windows

### 问题描述

获取列表失败 TypeError: Failed to fetch

### 重现步骤

点击刷新
获取列表失败 TypeError: Failed to fetch

**Comment by ltxhhz** [comment]
代理或镜像用了吗

**Comment by lettimepassby** [comment]
> 代理或镜像用了吗

使用了代理，代理是正常的

**Comment by ltxhhz** [comment]
设置截图看看

**Comment by lettimepassby** [comment]
> 设置截图看看

![image](https://github.com/user-attachments/assets/22f76169-9aa8-41c0-bab6-d30c69960f78)
![image](https://github.com/user-attachments/assets/820cdd13-cafe-4222-85b6-476fffabaeba)
![image](https://github.com/user-attachments/assets/88b65518-5fa2-43a2-99ba-fb97152477b2)
代理运行正常

**Comment by ltxhhz** [comment]
![image](https://github.com/user-attachments/assets/b5802486-647c-4b31-9e6f-302586d317fc)
你都没开代理

**Comment by ltxhhz** [comment]
![image](https://github.com/user-attachments/assets/753b5897-caf8-46e4-a42b-38bd948c305a)
正常页面

**Comment by lettimepassby** [comment]
🥲抱歉，没看见这个按钮
