### ISSUE TITLE
[feature] 加速列表加载速度的潜在方案

### ISSUE THREAD

**Issue by CarlGao4** [ltxhhz/LL-plugin-list-viewer#48]
### qq版本

9.9.6-28788

### LiteLoader 版本

1.2.2

### 版本信息

![image](https://github.com/user-attachments/assets/68e2f232-b0c5-4006-afaa-76e276b515ff)

### list-viewer 插件版本

1.4.3

### LiteLoader 是否为发布版本(release)

是

### 请描述您的需求或者改进建议

每个插件的详细信息是通过逐个fetch对应仓库里的manifest.json实现，但是目前有81个插件导致加载速度并不理想。可以利用GitHub Actions每2小时从所有插件的仓库拉取manifest并整合到同一个json中，这样只需要下载一个文件即可查看所有插件的详细信息，同时也可以避免个人GitHub Token使用太多次。

### 请描述你建议的实现方案

公开仓库的GitHub Actions完全免费，用定时任务即可实现自动刷新，且用户端延迟最多只有2小时。
如果使用github.io子域名提供文件下载，对大陆区用户将会更友好（github.io比github.com访问速度更快）

### 附加信息

如果需要帮助实现我也可以参与

**Comment by ltxhhz** [comment]
可以做，下周有时间我就做



---原始邮件---
发件人: "Weiqi ***@***.***&gt;
发送时间: 2024年11月24日(周日) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ltxhhz/LL-plugin-list-viewer] [feature] 加速列表加载速度的潜在方案 (Issue #48)




 
qq版本
 
9.9.6-28788
 
LiteLoader 版本
 
1.2.2
 
版本信息
 
image.png (view on web)
 
list-viewer 插件版本
 
1.4.3
 
LiteLoader 是否为发布版本(release)
 
是
 
请描述您的需求或者改进建议
 
每个插件的详细信息是通过逐个fetch对应仓库里的manifest.json实现，但是目前有81个插件导致加载速度并不理想。可以利用GitHub Actions每2小时从所有插件的仓库拉取manifest并整合到同一个json中，这样只需要下载一个文件即可查看所有插件的详细信息，同时也可以避免个人GitHub Token使用太多次。
 
请描述你建议的实现方案
 
公开仓库的GitHub Actions完全免费，用定时任务即可实现自动刷新，且用户端延迟最多只有2小时。
 如果使用github.io子域名提供文件下载，对大陆区用户将会更友好（github.io比github.com访问速度更快）
 
附加信息
 
如果需要帮助实现我也可以参与

**Comment by CarlGao4** [comment]
包括插件的图标也可以拼成雪碧图（但是最好是png格式可以保留透明度，具体怎样转换还不是很确定）（包括从svg转换，因为有的图标是svg的）（但是我想到了一种可行的解决方案，就是调用浏览器用canvas绘图）进一步提高加载速度

**Comment by ltxhhz** [comment]
18d1af85d9a2ae85f9ac38aff82c59eb9da31b0d 已经完成了，感谢你的建议

**Comment by CarlGao4** [comment]
好像目前默认设置还是通过逐个仓库访问来获取每个插件的信息的？
![image](https://github.com/user-attachments/assets/2b31f122-89c8-46c7-8616-7b43ae9fe23e)
感觉这个设置还是默认开启吧？

**Comment by ltxhhz** [comment]
默认关闭，需要开启
有些人可能就想要最新数据，每个人需求不一样，没必要替别人决定
