### ISSUE TITLE
安装插件之后，显示未激活，插件无法使用，不知道是插件的问题还是，插件列表的问题

### ISSUE THREAD

**Issue by MK-320** [ltxhhz/LL-plugin-list-viewer#49]
### 版本信息

![image](https://github.com/user-attachments/assets/4a00e18d-3183-4a67-891c-28a9df693288)

### list-viewer 插件版本

1.4.3

### LiteLoader 是否为发布版本(release)

是

### 使用平台

win11

### 问题描述

安装插件之后，显示未激活，插件无法使用，不知道是插件的问题还是，插件列表的问题
![image](https://github.com/user-attachments/assets/be77e66d-6a20-4ebf-9515-332e706ea76d)

### 重现步骤

暂时无需重现

**Comment by ltxhhz** [comment]
你把鼠标放到“未激活”上试试呢

**Comment by MK-320** [comment]
> 你把鼠标放到“未激活”上试试呢
试过了没有反应

**Comment by ltxhhz** [comment]
重启qq了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月25日(周一) 中午1:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ltxhhz/LL-plugin-list-viewer] 安装插件之后，显示未激活，插件无法使用，不知道是插件的问题还是，插件列表的问题 (Issue #49)




  
你把鼠标放到“未激活”上试试呢
 试过了没有反应

**Comment by MK-320** [comment]
> 重启qq了吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年11月25日(周一) 中午1:10 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ltxhhz/LL-plugin-list-viewer] 安装插件之后，显示未激活，插件无法使用，不知道是插件的问题还是，插件列表的问题 (Issue #49) 你把鼠标放到“未激活”上试试呢 试过了没有反应 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

重启之后好了，谢谢，我并不知道要重启之后才可以生效，上面也没写，建议加一下

**Comment by ltxhhz** [comment]
没反应？
![image](https://github.com/user-attachments/assets/3f9186a0-0d81-4e02-820d-45726535a5f3)

**Comment by MK-320** [comment]
> 没反应？ ![image](https://private-user-images.githubusercontent.com/51697596/389426251-3f9186a0-0d81-4e02-820d-45726535a5f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjExMjAsIm5iZiI6MTczMjUyMDgyMCwicGF0aCI6Ii81MTY5NzU5Ni8zODk0MjYyNTEtM2Y5MTg2YTAtMGQ4MS00ZTAyLTgyMGQtNDU3MjY1MzVhNWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA3NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkY2FkNzZmNmQ1NjdlMjRmMmVmMWE4ODc4M2ExMDY5ZjE3MTM0MzdkZGVhODg4ZGZiNWMwYWRjNGMxNGE3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0fLFt1T30KDT5s99pkNn_AIexgz7tLzaXLB9vWkWrW0)

我这里并没有这个“需要重启qq”的按钮，只有这个
![image](https://github.com/user-attachments/assets/673f6db9-1a84-4ced-b715-08d3a6c1fa53)
