### ISSUE TITLE
增加插件依赖关系提示

### ISSUE THREAD

**Issue by SpaceThing** [ltxhhz/LL-plugin-list-viewer#5]
希望能增加插件依赖关系提示，缺少依赖安装插件可能导致LiteLoader整体不被加载，容易误认为bug
如之前的插件商店
![zru2rfhe z04](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/17a804e7-bf51-417e-a34d-45938e623b1e)

**Comment by ltxhhz** [comment]
在做了在做了.jpg

**Comment by SpaceThing** [comment]
辛苦了！🙌
