### ISSUE TITLE
更新插件在海外似乎无法顺利下载

### ISSUE THREAD

**Issue by alrcatraz** [ltxhhz/LL-plugin-list-viewer#50]
### qq版本

9.9.16-29927

### LiteLoader 版本

1.2.3

### 版本信息

![image](https://github.com/user-attachments/assets/aecef4e2-1734-4d6a-a2c8-d3b7315a17dc)

### list-viewer 插件版本

1.4.3

### LiteLoader 是否为发布版本(release)

是

### 使用平台

windows 11 Pro

### 问题描述

我现在人在伦敦，插件可以顺利检查是否存在插件更新，但是下载更新时则会提示超时等问题，导致无法顺利更新各个插件

### 重现步骤

不确定……可能只是与网络有关？

### 附加信息

![image](https://github.com/user-attachments/assets/fce9e86b-8fb5-4351-b8a9-22ad70dc7cb5)
报错窗口如上

**Comment by ltxhhz** [comment]
你浏览器直接访问这个地址看看什么结果

**Comment by alrcatraz** [comment]
> 你浏览器直接访问这个地址看看什么结果

直接访问插件的项目页面都是正常的，也可以正常下载

**Comment by ltxhhz** [comment]
会看控制台吗，禁用缓存看下请求用时多久
还是浏览器里

**Comment by alrcatraz** [comment]
> 会看控制台吗，禁用缓存看下请求用时多久 还是浏览器里

怎么弄啊，cmd只用过ping🤔

**Comment by ltxhhz** [comment]
在打开上面url的页面，按f12，点到网络(network)，勾选禁用缓存(disable cache)，左边清除记录点一下，然后刷新页面，看这条url的用时

**Comment by ltxhhz** [comment]
实在不会的话你在当前这个github的页面按f12，选控制台(console)，然后把这段代码贴进去，看结果
```js
async function measureRequestTime(url) {
  const startTime = performance.now()
  try {
    const response = await fetch(url)
    const endTime = performance.now()

    if (response.ok) {
      console.log(`耗时: ${(endTime - startTime).toFixed(2)} 毫秒`);
    } else {
      console.error("请求失败！状态码:", response.status)
    }
  } catch (error) {
    console.error("请求出错:", error);
  }
}

measureRequestTime('https://api.github.com/repos/PRO-2684/transitio/releases/latest')

```

**Comment by ltxhhz** [comment]
按理来说不超过3s就不会有问题

**Comment by alrcatraz** [comment]
> 实在不会的话你在当前这个github的页面按f12，选控制台(console)，然后把这段代码贴进去，看结果
> 
> ```js
> async function measureRequestTime(url) {
>   const startTime = performance.now()
>   try {
>     const response = await fetch(url)
>     const endTime = performance.now()
> 
>     if (response.ok) {
>       console.log(`耗时: ${(endTime - startTime).toFixed(2)} 毫秒`);
>     } else {
>       console.error("请求失败！状态码:", response.status)
>     }
>   } catch (error) {
>     console.error("请求出错:", error);
>   }
> }
> 
> measureRequestTime('https://api.github.com/repos/PRO-2684/transitio/releases/latest')
> ```

![image](https://github.com/user-attachments/assets/42071eae-b613-4dbd-8284-49d19c77360f)

**Comment by ltxhhz** [comment]
截图看下你的配置

**Comment by alrcatraz** [comment]
![image](https://github.com/user-attachments/assets/010f23fc-df5a-4fc8-8b68-39dec1d80733)
![image](https://github.com/user-attachments/assets/bff9dce8-d6aa-4c10-9b6e-e3474a948923)
![image](https://github.com/user-attachments/assets/6d49c5db-7195-4975-815a-23a2d3e63982)
![image](https://github.com/user-attachments/assets/b3c394c0-3145-492f-9e41-56f5d9910575)

**Comment by ltxhhz** [comment]
用最新版修改一下配置里的超时时间试试吧，你这个问题我想不通

**Comment by alrcatraz** [comment]
> 用最新版修改一下配置里的超时时间试试吧，你这个问题我想不通

好的，我回去试试看

**Comment by ltxhhz** [comment]
有问题请继续留言
