### ISSUE TITLE
不支持jsdelivr镜像

### ISSUE THREAD

**Issue by coolxitech** [ltxhhz/LL-plugin-list-viewer#52]
### qq版本

9.9.16-29725

### LiteLoader 版本

1.2.3

### list-viewer 插件版本

1.3.10

### LiteLoader 是否为发布版本(release)

是

### 使用平台

Windows

### 问题描述

通过请求的地址无法访问到plugins.json文件。
`https://cdn.jsdelivr.net/gh/LiteLoaderQQNT/raw/v4/plugins.json`
返回`Failed to fetch version info for LiteLoaderQQNT/raw.`
建议更换请求地址,有用的地址如下:
`https://cdn.jsdelivr.net/gh/LiteLoaderQQNT/Plugin-List@v4/plugins.json`

### 重现步骤

在插件的设置里打开是否使用镜像地址,点击刷新无法刷新出列表

**Comment by ltxhhz** [comment]
现在都 1.5.0 版本了
