### ISSUE TITLE
安装失败后恢复安装按钮

### ISSUE THREAD

**Issue by SpaceThing** [ltxhhz/LL-plugin-list-viewer#6]
不知道为什么经常仓库/release之一安装失败，失败后安装按钮保持为“安装中”无法再次点击，需要手动刷新

![fjx3sqtt apn](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/e1c16156-3705-4f6a-9668-366b82b67335)
![ek14ptg0 2pa](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/ca9efeeb-ae2d-490c-9a17-533d99304127)

**Comment by SpaceThing** [comment]
不知道为什么经常仓库/release之一安装失败，只能刷新后选另一个😂

**Comment by SpaceThing** [comment]
叠一个楼，白天模式下新增的旧版本兼容显示，亮黄色字体不易辨认
![j0oartek cja](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/61451659/ab1cae11-03d9-4dba-b78c-41e3bd7fce8a)

**Comment by ltxhhz** [comment]
ok

**Comment by ltxhhz** [comment]
- 按钮问题应该在这条 issue 之前的最新版本已经修复了
- 颜色问题下个版本会改

**Comment by SpaceThing** [comment]
> * 按钮问题应该在这条 issue 之前的最新版本已经修复了
> * 颜色问题下个版本会改

重装了一下插件按钮确实好了，估计是因为我用新版安装器重装了LL，插件目录变到document了没加载上
