### ISSUE TITLE
请问我提交的问题 为什么被关闭了？ 有解决方法吗？

### ISSUE THREAD

**Issue by xingleiwu** [ltxhhz/LL-plugin-list-viewer#7]
https://github.com/ltxhhz/LL-plugin-list-viewer/issues/4
麻烦大佬了  我可以全力配合检查  不清楚为什么会被关闭

**Comment by ltxhhz** [comment]
![image](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/51697596/966501ba-600f-4bba-9c80-e081eac01f94)
引用意思是在那条提交已经被修复了，fixed 意思是已修复

而且在你之前已经有一个相同的issue，你不应该重开一个，这条issue也不应该再开，就算关闭的 issue 我也可以看到留言

**Comment by xingleiwu** [comment]
哦哦 明白了 麻烦您了 谢谢您  我在重新安装试试

**Comment by xingleiwu** [comment]
谢谢您 确实解决了 麻烦您了
