### ISSUE TITLE
滚动到最底部时显示异常

### ISSUE THREAD

**Issue by jy02534655** [ltxhhz/LL-plugin-list-viewer#8]
[video-convert-1716177405949.webm](https://github.com/ltxhhz/LL-plugin-list-viewer/assets/4277777/84a446bb-fa10-4b25-84d4-2c23718b4e6e)
看视频，最后一行一直在抖动，大概第3秒开始

**Comment by jy02534655** [comment]
更新qqnt版本到最新版后好像又正常了

**Comment by ltxhhz** [comment]
这个是bug，我会修的
